// AUTO-GENERATED by compile.py
#include "ptx_lib/ptx_common.cuh"
#include "ptx_lib/ptx_tma.cuh"
#include "ptx_lib/ptx_mbarrier.cuh"
#include "ptx_lib/ptx_tcgen05_cp.cuh"
#include "ptx_lib/ptx_tcgen05_mma.cuh"
#include "ptx_lib/ptx_tcgen05_ldst.cuh"
#include "ptx_lib/ptx_tcgen05_sync.cuh"

extern "C" __global__ void kernel_entry() {
  // TODO: emit DSL ops here (no raw PTX).
}
