#!/usr/bin/env python3
"""Build submission.py from cuda_lib + ptx_lib/*.cuh.

Expected inputs (relative to repo root by default):
  - cuda_lib/python.py (must reference CUDA_SRC)
  - cuda_lib/host.cuh
  - cuda_lib/device.cuh
  - ptx_lib/*.cuh

Use --compile to regenerate cuda_lib/* via compile.py.

This script only assembles submission.py; it does not run benchmarks.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent
REPO_ROOT = ROOT.parent
# ptx_lib lives at repo root (not nested under submission/)
PTX_LIB = REPO_ROOT / "ptx_lib"
COMPILER = ROOT / "compile.py"

# Strip local ptx_lib includes since we inline headers into CUDA_SRC.
_PTX_INCLUDE_PREFIXES = (
    '#include "ptx_lib/',
    '#include "ptx_',
    '#include <ptx_',
)


def _strip_ptx_includes(text: str) -> str:
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if any(stripped.startswith(prefix) for prefix in _PTX_INCLUDE_PREFIXES):
            continue
        lines.append(line)
    return "\n".join(lines)


def _read_text(path: Path) -> str:
    return path.read_text()


def _build_submission_from_cuda_lib(
    python_path: Path,
    host_path: Path,
    device_path: Path,
    out_path: Path,
) -> None:
    if not python_path.exists():
        raise FileNotFoundError(f"python snippet not found: {python_path}")
    if not host_path.exists():
        raise FileNotFoundError(f"host snippet not found: {host_path}")
    if not device_path.exists():
        raise FileNotFoundError(f"device snippet not found: {device_path}")
    if not PTX_LIB.exists():
        raise FileNotFoundError(f"ptx_lib not found: {PTX_LIB}")

    ptx_headers = sorted(PTX_LIB.glob("*.cuh"))
    if not ptx_headers:
        raise FileNotFoundError(f"No .cuh files found in {PTX_LIB}")

    # Prefer ptx_common.cuh first if present.
    ptx_headers = sorted(
        ptx_headers,
        key=lambda p: (p.name != "ptx_common.cuh", p.name),
    )

    parts: List[str] = []
    parts.append("# AUTO-GENERATED by run.py\n")
    parts.append("# Do not edit directly; edit cuda_lib/* and ptx_lib/*.cuh instead.\n\n")
    parts.append("CUDA_SRC = r'''\n")

    for header in ptx_headers:
        parts.append(f"// ----- {header.name} -----\n")
        parts.append(_read_text(header))
        if not parts[-1].endswith("\n"):
            parts.append("\n")
        parts.append("\n")

    parts.append("// ----- device.cuh -----\n")
    parts.append(_strip_ptx_includes(_read_text(device_path)))
    if not parts[-1].endswith("\n"):
        parts.append("\n")

    parts.append("// ----- host.cuh -----\n")
    parts.append(_strip_ptx_includes(_read_text(host_path)))
    if not parts[-1].endswith("\n"):
        parts.append("\n")

    parts.append("'''\n\n")

    # Append python snippet verbatim; it should reference CUDA_SRC
    parts.append(_strip_ptx_includes(_read_text(python_path)))
    if not parts[-1].endswith("\n"):
        parts.append("\n")

    out_path.write_text("".join(parts))


def main() -> int:
    parser = argparse.ArgumentParser(description="Build submission.py")
    parser.add_argument("--snippets-dir", default="cuda_lib", help="Directory containing python.py/host.cuh/device.cuh")
    parser.add_argument("--python", default="python.py", help="Python snippet filename")
    parser.add_argument("--host", default="host.cuh", help="Host snippet filename")
    parser.add_argument("--device", default="device.cuh", help="Device snippet filename")
    parser.add_argument("--out", default="submission.py", help="Output submission.py path")
    parser.add_argument("--compile", action="store_true", help="Run compile.py to regenerate cuda_lib/*")
    parser.add_argument("--build-only", action="store_true", help="Only build submission.py")
    parser.add_argument("args", nargs=argparse.REMAINDER, help="Unused; kept for compatibility")
    args = parser.parse_args()

    snippets_dir = (REPO_ROOT / args.snippets_dir).resolve()
    python_path = snippets_dir / args.python
    host_path = snippets_dir / args.host
    device_path = snippets_dir / args.device
    out_path = (ROOT / args.out).resolve()

    if args.compile:
        if not COMPILER.exists():
            raise FileNotFoundError(f"compile.py not found: {COMPILER}")
        ret = subprocess.call([sys.executable, str(COMPILER)])
        if ret != 0:
            raise SystemExit(ret)

    _build_submission_from_cuda_lib(python_path, host_path, device_path, out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
